# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoCaptureGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import cv2
import time, queue, threading
import keyboard
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QPoint, QSize
from PyQt5.Qt import *

cwd = os.getcwd()

WINDOW_SIZE = 0;
CURRENT_INDEX_PAGE = 1;
CAMERA_ON = True
RECORD_ON = False
FIRST_PRESS = True

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1558, 1252)
        MainWindow.setMinimumSize(QtCore.QSize(1400, 720))
        
        flags = QtCore.Qt.WindowFlags(QtCore.Qt.FramelessWindowHint)
        
        MainWindow.setWindowFlags(flags)
        MainWindow.setMouseTracking(True)
        
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow {background: transparent; }\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(27, 29, 35, 160);\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    border-radius: 2px;\n"
"}")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: transparent;\n"
"color: rgb(210, 210, 210);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setStyleSheet("/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* SCROLL BARS */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
"}\n"
"\n"
"/* RADIO BUTTON */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/icons/16x16/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 9px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"")
        self.frame_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.frame_main)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_top.setStyleSheet("background-color: transparent;")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_logo = QtWidgets.QFrame(self.frame_top)
        self.frame_logo.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_logo.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_logo.setObjectName("frame_logo")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_logo)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_logo = QtWidgets.QPushButton(self.frame_logo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_logo.sizePolicy().hasHeightForWidth())
        self.btn_logo.setSizePolicy(sizePolicy)
        self.btn_logo.setAutoFillBackground(False)
        self.btn_logo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Downloads/icon-1.1s-200px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_logo.setIcon(icon)
        self.btn_logo.setIconSize(QtCore.QSize(60, 60))
        self.btn_logo.setCheckable(False)
        self.btn_logo.setObjectName("btn_logo")
        self.verticalLayout_3.addWidget(self.btn_logo)
        self.horizontalLayout_3.addWidget(self.frame_logo)
        self.frame_top_right = QtWidgets.QFrame(self.frame_top)
        self.frame_top_right.setMouseTracking(True)
        self.frame_top_right.setAcceptDrops(True)
        self.frame_top_right.setStyleSheet("background: transparent;")
        self.frame_top_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_right.setObjectName("frame_top_right")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_top_right)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top_btns = QtWidgets.QFrame(self.frame_top_right)
        self.frame_top_btns.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_top_btns.setStyleSheet("background-color: rgba(27, 29, 35, 200)")
        self.frame_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_btns.setObjectName("frame_top_btns")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_btns)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_label_top_btns = QtWidgets.QFrame(self.frame_top_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_top_btns.sizePolicy().hasHeightForWidth())
        self.frame_label_top_btns.setSizePolicy(sizePolicy)
        self.frame_label_top_btns.setMouseTracking(True)
        self.frame_label_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_top_btns.setObjectName("frame_label_top_btns")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_label_top_btns)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_title_bar_top = QtWidgets.QLabel(self.frame_label_top_btns)
        self.label_title_bar_top.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_bar_top.setFont(font)
        self.label_title_bar_top.setMouseTracking(True)
        self.label_title_bar_top.setAcceptDrops(True)
        self.label_title_bar_top.setObjectName("label_title_bar_top")
        self.horizontalLayout_10.addWidget(self.label_title_bar_top)
        self.horizontalLayout_4.addWidget(self.frame_label_top_btns)
        self.frame_btns_right = QtWidgets.QFrame(self.frame_top_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_btns_right.sizePolicy().hasHeightForWidth())
        self.frame_btns_right.setSizePolicy(sizePolicy)
        self.frame_btns_right.setMaximumSize(QtCore.QSize(160, 16777215))
        self.frame_btns_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns_right.setObjectName("frame_btns_right")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_btns_right)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_hide_config = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_hide_config.sizePolicy().hasHeightForWidth())
        self.btn_hide_config.setSizePolicy(sizePolicy)
        self.btn_hide_config.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_hide_config.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_hide_config.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.btn_hide_config.setStyleSheet("")
        self.btn_hide_config.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/16x16/cil-zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_hide_config.setIcon(icon1)
        self.btn_hide_config.setCheckable(False)
        self.btn_hide_config.setObjectName("btn_hide_config")
        self.horizontalLayout_5.addWidget(self.btn_hide_config)
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_minimize.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_minimize.setStyleSheet("")
        self.btn_minimize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/16x16/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon2)
        self.btn_minimize.setCheckable(False)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_5.addWidget(self.btn_minimize)
        self.btn_maximize_restore = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_maximize_restore.sizePolicy().hasHeightForWidth())
        self.btn_maximize_restore.setSizePolicy(sizePolicy)
        self.btn_maximize_restore.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_maximize_restore.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_maximize_restore.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/16x16/cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximize_restore.setIcon(icon3)
        self.btn_maximize_restore.setObjectName("btn_maximize_restore")
        self.horizontalLayout_5.addWidget(self.btn_maximize_restore)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_close.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_close.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/16x16/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon4)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_5.addWidget(self.btn_close)
        self.horizontalLayout_4.addWidget(self.frame_btns_right)
        self.verticalLayout_2.addWidget(self.frame_top_btns)
        self.horizontalLayout_3.addWidget(self.frame_top_right)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_center = QtWidgets.QFrame(self.frame_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_center.sizePolicy().hasHeightForWidth())
        self.frame_center.setSizePolicy(sizePolicy)
        self.frame_center.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_center)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.frame_center)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left_menu.sizePolicy().hasHeightForWidth())
        self.frame_left_menu.setSizePolicy(sizePolicy)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_left_menu.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_5.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_menus.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menus.setObjectName("frame_menus")
        self.layout_menus = QtWidgets.QVBoxLayout(self.frame_menus)
        self.layout_menus.setContentsMargins(0, 0, 0, 0)
        self.layout_menus.setSpacing(0)
        self.layout_menus.setObjectName("layout_menus")
        self.verticalLayout_5.addWidget(self.frame_menus, 0, QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.frame_left_menu)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 200))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.CurrentCameraID = QtWidgets.QSpinBox(self.frame)
        self.CurrentCameraID.setGeometry(QtCore.QRect(0, 22, 70, 20))
        self.CurrentCameraID.setMaximumSize(QtCore.QSize(70, 16777215))
        self.CurrentCameraID.setWrapping(False)
        self.CurrentCameraID.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentCameraID.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.CurrentCameraID.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.CurrentCameraID.setObjectName("CurrentCameraID")
        self.CameraIDLabel = QtWidgets.QLabel(self.frame)
        self.CameraIDLabel.setGeometry(QtCore.QRect(0, 0, 70, 20))
        self.CameraIDLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CameraIDLabel.setObjectName("CameraIDLabel")
        self.SwitchToFiles = QtWidgets.QLabel(self.frame)
        self.SwitchToFiles.setGeometry(QtCore.QRect(5, 60, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SwitchToFiles.sizePolicy().hasHeightForWidth())
        self.SwitchToFiles.setSizePolicy(sizePolicy)
        self.SwitchToFiles.setMinimumSize(QtCore.QSize(60, 60))
        self.SwitchToFiles.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.SwitchToFiles.setFont(font)
        self.SwitchToFiles.setStyleSheet("QLabel {\n"
"    border-radius: 30px;\n"
"    background-color: rgb(44, 49, 60);\n"
"    border: 5px solid rgb(39, 44, 54);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}")
        self.SwitchToFiles.setText("")
        self.SwitchToFiles.setPixmap(QtGui.QPixmap("icons/16x16/cil-camera.png"))
        self.SwitchToFiles.setAlignment(QtCore.Qt.AlignCenter)
        self.SwitchToFiles.setObjectName("SwitchToFiles")
        self.SwitchToFiles_2 = QtWidgets.QLabel(self.frame)
        self.SwitchToFiles_2.setGeometry(QtCore.QRect(5, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SwitchToFiles_2.sizePolicy().hasHeightForWidth())
        self.SwitchToFiles_2.setSizePolicy(sizePolicy)
        self.SwitchToFiles_2.setMinimumSize(QtCore.QSize(60, 60))
        self.SwitchToFiles_2.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.SwitchToFiles_2.setFont(font)
        self.SwitchToFiles_2.setStyleSheet("QLabel {\n"
"    border-radius: 30px;\n"
"    background-color: rgb(44, 49, 60);\n"
"    border: 5px solid rgb(39, 44, 54);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}")
        self.SwitchToFiles_2.setText("")
        self.SwitchToFiles_2.setPixmap(QtGui.QPixmap("icons/16x16/cil-file.png"))
        self.SwitchToFiles_2.setAlignment(QtCore.Qt.AlignCenter)
        self.SwitchToFiles_2.setObjectName("SwitchToFiles_2")
        self.verticalLayout_5.addWidget(self.frame)
        self.frame_extra_menus = QtWidgets.QFrame(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_extra_menus.sizePolicy().hasHeightForWidth())
        self.frame_extra_menus.setSizePolicy(sizePolicy)
        self.frame_extra_menus.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_extra_menus.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_extra_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_extra_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_extra_menus.setObjectName("frame_extra_menus")
        self.layout_menu_bottom = QtWidgets.QVBoxLayout(self.frame_extra_menus)
        self.layout_menu_bottom.setContentsMargins(0, 5, 0, 5)
        self.layout_menu_bottom.setSpacing(10)
        self.layout_menu_bottom.setObjectName("layout_menu_bottom")
        self.label_user_icon = QtWidgets.QLabel(self.frame_extra_menus)
        self.label_user_icon.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_user_icon.sizePolicy().hasHeightForWidth())
        self.label_user_icon.setSizePolicy(sizePolicy)
        self.label_user_icon.setMinimumSize(QtCore.QSize(60, 60))
        self.label_user_icon.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_user_icon.setFont(font)
        self.label_user_icon.setStyleSheet("QLabel {\n"
"    border-radius: 30px;\n"
"    background-color: rgb(44, 49, 60);\n"
"    border: 5px solid rgb(39, 44, 54);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}")
        self.label_user_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user_icon.setWordWrap(True)
        self.label_user_icon.setObjectName("label_user_icon")
        self.layout_menu_bottom.addWidget(self.label_user_icon)
        self.verticalLayout_5.addWidget(self.frame_extra_menus)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_content_right = QtWidgets.QFrame(self.frame_center)
        self.frame_content_right.setStyleSheet("background-color: rgb(44, 49, 60);")
        self.frame_content_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_right.setObjectName("frame_content_right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_content_right)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_content = QtWidgets.QFrame(self.frame_content_right)
        self.frame_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_content)
        self.verticalLayout_9.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_content)
        self.stackedWidget.setMinimumSize(QtCore.QSize(49, 50))
        self.stackedWidget.setAcceptDrops(False)
        self.stackedWidget.setStyleSheet("background: transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_full_screen = QtWidgets.QWidget()
        self.page_full_screen.setObjectName("page_full_screen")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_full_screen)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_9 = QtWidgets.QWidget(self.page_full_screen)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        # self.openGLWidget_2 = QtWidgets.QOpenGLWidget(self.widget_9)
        self.image_frame_hideConfig = QtWidgets.QLabel(self.widget_9)
        self.image_frame_hideConfig.setAlignment(QtCore.Qt.AlignCenter)

        self.image_frame_hideConfig.setMinimumSize(QtCore.QSize(1920, 1080))
        self.image_frame_hideConfig.setMaximumSize(QtCore.QSize(1920, 1080))
        self.image_frame_hideConfig.setAutoFillBackground(False)
        self.image_frame_hideConfig.setObjectName("image_frame_hideConfig")
        
        self.gridLayout_8.addWidget(self.image_frame_hideConfig, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.widget_9)
        self.verticalLayout_10.addWidget(self.widget_9)
        self.stackedWidget.addWidget(self.page_full_screen)
        
        self.page_camera_1 = QtWidgets.QWidget()
        self.page_camera_1.setObjectName("page_camera_1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_camera_1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.page_camera_1)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 65))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_2.setStyleSheet("background-color: rgb(39, 44, 54);\n"
"border-radius: 5px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(600, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.StopCamera = QtWidgets.QPushButton(self.widget_2)
        self.StopCamera.setEnabled(True)
        self.StopCamera.setGeometry(QtCore.QRect(240, 16, 150, 30))
        self.StopCamera.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.StopCamera.setFont(font)
        self.StopCamera.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.StopCamera.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/16x16/cil-media-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StopCamera.setIcon(icon5)
        self.StopCamera.setObjectName("StopCamera")
        self.StartCameras = QtWidgets.QPushButton(self.widget_2)
        self.StartCameras.setEnabled(True)
        self.StartCameras.setGeometry(QtCore.QRect(40, 16, 150, 30))
        self.StartCameras.setMinimumSize(QtCore.QSize(150, 30))
        self.StartCameras.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.StartCameras.setFont(font)
        self.StartCameras.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.StartCameras.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/16x16/cil-media-play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StartCameras.setIcon(icon6)
        self.StartCameras.setObjectName("StartCameras")
        self.captureFolder = QtWidgets.QLineEdit(self.widget_2)
        self.captureFolder.setGeometry(QtCore.QRect(640, 16, 600, 30))
        self.captureFolder.setObjectName("captureFolder")
        self.ProcessVideoFile_5 = QtWidgets.QPushButton(self.widget_2)
        self.ProcessVideoFile_5.setEnabled(True)
        self.ProcessVideoFile_5.setGeometry(QtCore.QRect(440, 16, 150, 30))
        self.ProcessVideoFile_5.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.ProcessVideoFile_5.setFont(font)
        self.ProcessVideoFile_5.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.ProcessVideoFile_5.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/16x16/cil-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ProcessVideoFile_5.setIcon(icon7)
        self.ProcessVideoFile_5.setObjectName("ProcessVideoFile_5")
        self.gridLayout_2.addWidget(self.widget_2, 1, 2, 1, 1)
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setMinimumSize(QtCore.QSize(200, 50))
        self.widget.setMaximumSize(QtCore.QSize(200, 180))
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setContentsMargins(9, 9, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_8 = QtWidgets.QWidget(self.widget)
        self.widget_8.setObjectName("widget_8")
        self.RecordButton3 = QtWidgets.QRadioButton(self.widget_8)
        self.RecordButton3.setGeometry(QtCore.QRect(5, 7, 162, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.RecordButton3.setFont(font)
        self.RecordButton3.setObjectName("RecordButton3")
        self.gridLayout_5.addWidget(self.widget_8, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 1, 3, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_2)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.page_camera_1)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        # self.openGLWidget = QtWidgets.QOpenGLWidget(self.frame_3)
        self.image_frame = QtWidgets.QLabel(self.frame_3)
        self.image_frame.setAlignment(QtCore.Qt.AlignCenter)

        self.image_frame.setMinimumSize(QtCore.QSize(1920, 1080))
        self.image_frame.setMaximumSize(QtCore.QSize(1920, 1080))
        self.image_frame_hideConfig.setAutoFillBackground(False)
        self.image_frame.setObjectName("image_frame")
        # openGLLabel.setPixmap(QPixmap.fromImage(image))
        
        self.horizontalLayout_12.addWidget(self.image_frame)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.page_camera_1)
        
        self.page_camera_2 = QtWidgets.QWidget()
        self.page_camera_2.setObjectName("page_camera_2")
        
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_camera_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        
        self.frame_5 = QtWidgets.QFrame(self.page_camera_2)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_5.setObjectName("frame_5")
        
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")

        # self.openGLWidget_3 = QtWidgets.QOpenGLWidget(self.frame_5)
        
        self.image_frame2 = QtWidgets.QLabel(self.frame_5)
        self.image_frame2.setAlignment(QtCore.Qt.AlignCenter)

        self.image_frame2.setMinimumSize(QtCore.QSize(1920, 1080))
        self.image_frame2.setMaximumSize(QtCore.QSize(1920, 1080))
        self.image_frame2.setObjectName("image_frame2")
        # openGLLabel.setPixmap(QPixmap.fromImage(image))
        
        self.horizontalLayout_13.addWidget(self.image_frame2)
        
        # self.verticalLayout_14.addWidget(self.frame_5)
        
        self.frame_4 = QtWidgets.QFrame(self.page_camera_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1920, 65))
        self.frame_4.setMinimumSize(QtCore.QSize(1920, 65))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_4.setStyleSheet("background-color: rgb(39, 44, 54);\n"
"border-radius: 5px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setHorizontalSpacing(6)
        self.gridLayout_10.setVerticalSpacing(2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        
        self.widget_7 = QtWidgets.QWidget(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(600, 0))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_7.setObjectName("widget_7")
        
        self.StopCamera2 = QtWidgets.QPushButton(self.widget_7)
        self.StopCamera2.setEnabled(True)
        self.StopCamera2.setGeometry(QtCore.QRect(240, 16, 150, 30))
        self.StopCamera2.setMinimumSize(QtCore.QSize(150, 30))
        
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)

        self.StopCamera2.setFont(font)
        self.StopCamera2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.StopCamera2.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.StopCamera2.setIcon(icon5)
        self.StopCamera2.setObjectName("StopCamera2")
        self.StartCameras2 = QtWidgets.QPushButton(self.widget_7)
        self.StartCameras2.setEnabled(True)
        self.StartCameras2.setGeometry(QtCore.QRect(40, 16, 150, 30))
        self.StartCameras2.setMinimumSize(QtCore.QSize(150, 30))
        self.StartCameras2.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.StartCameras2.setFont(font)
        self.StartCameras2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.StartCameras2.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.StartCameras2.setIcon(icon6)
        self.StartCameras2.setObjectName("StartCameras2")
        self.captureFolder_4 = QtWidgets.QLineEdit(self.widget_7)
        self.captureFolder_4.setGeometry(QtCore.QRect(640, 16, 600, 30))
        self.captureFolder_4.setObjectName("captureFolder_4")
        self.ProcessVideoFile_12 = QtWidgets.QPushButton(self.widget_7)
        self.ProcessVideoFile_12.setEnabled(True)
        self.ProcessVideoFile_12.setGeometry(QtCore.QRect(440, 16, 150, 30))
        self.ProcessVideoFile_12.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.ProcessVideoFile_12.setFont(font)
        self.ProcessVideoFile_12.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.ProcessVideoFile_12.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.ProcessVideoFile_12.setIcon(icon7)
        self.ProcessVideoFile_12.setObjectName("ProcessVideoFile_12")
        self.gridLayout_10.addWidget(self.widget_7, 1, 2, 1, 1)
        self.widget_12 = QtWidgets.QWidget(self.frame_4)
        self.widget_12.setMinimumSize(QtCore.QSize(200, 50))
        self.widget_12.setMaximumSize(QtCore.QSize(200, 180))
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_12)
        self.gridLayout_11.setContentsMargins(9, 9, -1, -1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.widget_13 = QtWidgets.QWidget(self.widget_12)
        self.widget_13.setObjectName("widget_13")
        self.RecordButton = QtWidgets.QRadioButton(self.widget_13)
        self.RecordButton.setGeometry(QtCore.QRect(5, 7, 162, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.RecordButton.setFont(font)
        self.RecordButton.setObjectName("RecordButton")
        self.gridLayout_11.addWidget(self.widget_13, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.widget_12, 1, 3, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_10)
        self.verticalLayout_7.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.page_camera_2)
        
        self.page_file_dialog = QtWidgets.QWidget()
        self.page_file_dialog.setObjectName("page_file_dialog")
        self.frame_6 = QtWidgets.QFrame(self.page_file_dialog)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 1472, 65))
        self.frame_6.setMinimumSize(QtCore.QSize(0, 65))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_6.setStyleSheet("background-color: rgb(39, 44, 54);\n"
"border-radius: 5px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setVerticalSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_5 = QtWidgets.QWidget(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(600, 0))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_5.setObjectName("widget_5")
        self.ProcessVideoFile_6 = QtWidgets.QPushButton(self.widget_5)
        self.ProcessVideoFile_6.setEnabled(True)
        self.ProcessVideoFile_6.setGeometry(QtCore.QRect(240, 16, 150, 30))
        self.ProcessVideoFile_6.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.ProcessVideoFile_6.setFont(font)
        self.ProcessVideoFile_6.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.ProcessVideoFile_6.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.ProcessVideoFile_6.setIcon(icon5)
        self.ProcessVideoFile_6.setObjectName("ProcessVideoFile_6")
        self.ProcessVideoFile_7 = QtWidgets.QPushButton(self.widget_5)
        self.ProcessVideoFile_7.setEnabled(True)
        self.ProcessVideoFile_7.setGeometry(QtCore.QRect(40, 16, 150, 30))
        self.ProcessVideoFile_7.setMinimumSize(QtCore.QSize(150, 30))
        self.ProcessVideoFile_7.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.ProcessVideoFile_7.setFont(font)
        self.ProcessVideoFile_7.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.ProcessVideoFile_7.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.ProcessVideoFile_7.setIcon(icon6)
        self.ProcessVideoFile_7.setObjectName("ProcessVideoFile_7")
        self.captureFolder_2 = QtWidgets.QLineEdit(self.widget_5)
        self.captureFolder_2.setGeometry(QtCore.QRect(640, 16, 600, 30))
        self.captureFolder_2.setObjectName("captureFolder_2")
        self.ProcessVideoFile_8 = QtWidgets.QPushButton(self.widget_5)
        self.ProcessVideoFile_8.setEnabled(True)
        self.ProcessVideoFile_8.setGeometry(QtCore.QRect(440, 16, 150, 30))
        self.ProcessVideoFile_8.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.ProcessVideoFile_8.setFont(font)
        self.ProcessVideoFile_8.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.ProcessVideoFile_8.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.ProcessVideoFile_8.setIcon(icon7)
        self.ProcessVideoFile_8.setObjectName("ProcessVideoFile_8")
        self.gridLayout_4.addWidget(self.widget_5, 1, 2, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.frame_6)
        self.widget_6.setMinimumSize(QtCore.QSize(200, 50))
        self.widget_6.setMaximumSize(QtCore.QSize(200, 180))
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_9.setContentsMargins(9, 9, -1, -1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget_11 = QtWidgets.QWidget(self.widget_6)
        self.widget_11.setObjectName("widget_11")
        self.RecordButton2 = QtWidgets.QRadioButton(self.widget_11)
        self.RecordButton2.setGeometry(QtCore.QRect(5, 7, 162, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.RecordButton2.setFont(font)
        self.RecordButton2.setObjectName("RecordButton2")
        self.gridLayout_9.addWidget(self.widget_11, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_6, 1, 3, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_4)
        self.stackedWidget.addWidget(self.page_file_dialog)
        
        self.verticalLayout_9.addWidget(self.stackedWidget)
        self.verticalLayout_4.addWidget(self.frame_content)
        self.frame_grip = QtWidgets.QFrame(self.frame_content_right)
        self.frame_grip.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_grip.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_grip.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_grip)
        self.horizontalLayout_6.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_label_bottom = QtWidgets.QFrame(self.frame_grip)
        self.frame_label_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_bottom.setObjectName("frame_label_bottom")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_label_bottom)
        self.horizontalLayout_7.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_credits = QtWidgets.QLabel(self.frame_label_bottom)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_7.addWidget(self.label_credits)
        self.label_version = QtWidgets.QLabel(self.frame_label_bottom)
        self.label_version.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_version.setAlignment(QtCore.Qt.AlignCenter)
        self.label_version.setObjectName("label_version")
        self.horizontalLayout_7.addWidget(self.label_version)
        self.horizontalLayout_6.addWidget(self.frame_label_bottom)
        self.frame_size_grip = QtWidgets.QFrame(self.frame_grip)
        self.frame_size_grip.setMaximumSize(QtCore.QSize(20, 20))
        self.frame_size_grip.setCursor(QtGui.QCursor(QtCore.Qt.SizeFDiagCursor))
        self.frame_size_grip.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.frame_size_grip.setAutoFillBackground(False)
        self.frame_size_grip.setStyleSheet("QSizeGrip {\\n\n"
"background-image: url(:/icons/16x16/cil-size-grip.png);\\n\n"
"background-position: center;\\n\n"
"background-repeat: no-reperat;\\n\n"
"}")
        self.frame_size_grip.setInputMethodHints(QtCore.Qt.ImhNone)
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_6.addWidget(self.frame_size_grip)
        self.verticalLayout_4.addWidget(self.frame_grip)
        self.horizontalLayout_2.addWidget(self.frame_content_right)
        self.verticalLayout.addWidget(self.frame_center)
        self.gridLayout_7.addWidget(self.frame_main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSelectFile = QtWidgets.QAction(MainWindow)
        self.actionSelectFile.setObjectName("actionSelectFile")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_maximize_restore, self.btn_close)
        MainWindow.setTabOrder(self.btn_close, self.btn_logo)
        
        
        ##### Button click events to our top bar buttons #####
        
        # Minimize window when clicked
        self.btn_minimize.clicked.connect(lambda: MainWindow.showMinimized())
        # Close window when clicked
        self.btn_close.clicked.connect(lambda: MainWindow.close())
        # Restore / Maximize window when clicked
        self.btn_maximize_restore.clicked.connect(lambda: self.restore_or_maximize_window())
        # Hide configuration window when clicked
        self.btn_hide_config.clicked.connect(lambda: self.hide_config_panel())
        # Real-time Camera - DSLR / Web Camera when clicked
        self.StartCameras.clicked.connect(lambda: self.StartTheCameras())
        # Real-time Camera - DSLR / Web Camera when clicked
        self.StartCameras2.clicked.connect(lambda: self.StartTheCameras())
        # Real-time Camera - DSLR / Web Camera when clicked
        self.StopCamera.clicked.connect(lambda: self.StopTheCameras())
        # Real-time Camera - DSLR / Web Camera when clicked
        self.StopCamera2.clicked.connect(lambda: self.StopTheCameras())
        # Real-time Camera - DSLR / Web Camera when clicked
        self.CurrentCameraID.valueChanged.connect(lambda: self.ChangeCamera())
        # Record Button - Toggles the record variable when clicked
        #self.RecordButton.toggled.connect(lambda: self.toggleRecord())
        # Record Button 2 - Toggles the record variable when clicked
        #self.RecordButton2.toggled.connect(lambda: self.toggleRecord())
        # Record Button 3 - Toggles the record variable when clicked
        self.RecordButton3.toggled.connect(lambda: self.toggleRecord())
        
        QSizeGrip(self.frame_size_grip)
        
        ##### Button click events to our top bar buttons #####
        
        
    def mousePressEvent(self, event):
        self.oldPosition = event.globalPosition()
        
    def mouseMoveEvent(self, event):
        delta = QPoint(event.globalPosition() - self.oldPosition)
        self.move(self.x() + delta.x(), self.y() + delta.y())
        self.oldPosition = event.globalPosition()

    def toggleFirstPress(self):
        FIRST_PRESS = False
    
    def hide_config_panel(self):
        global CURRENT_INDEX_PAGE
        
        print('Current page: ' + str(CURRENT_INDEX_PAGE))
        
        if CURRENT_INDEX_PAGE == 1:
            CURRENT_INDEX_PAGE = 0
            self.stackedWidget.setCurrentIndex(CURRENT_INDEX_PAGE)
            self.btn_hide_config.setIcon(QtGui.QIcon(cwd + "/icons/icons/cil-zoom-in.png"))#Show maximize icon
            print('Switched to page: ' + str(CURRENT_INDEX_PAGE))
        else:
            CURRENT_INDEX_PAGE = 1
            self.stackedWidget.setCurrentIndex(CURRENT_INDEX_PAGE)
            self.btn_hide_config.setIcon(QtGui.QIcon(cwd + "/icons/icons/cil-zoom-out.png"))#Show maximize icon
            print('Switched to page: ' + str(CURRENT_INDEX_PAGE))
            # MainWindow.move(0, 0)
            
    def toggleRecord(self):
        global RECORD_ON
        
        print('Record is currently set to: ' + str(RECORD_ON))
        
        if RECORD_ON == False:
            RECORD_ON = True
            self.RecordButton.setChecked(True)
            self.RecordButton2.setChecked(True)
            # self.RecordButton3.setChecked(True)
            print('Record is now set to: ' + str(RECORD_ON))
            
        else:
            RECORD_ON = False
            self.RecordButton.setChecked(False)
            self.RecordButton2.setChecked(False)
            # self.RecordButton3.setChecked(False)
            print('Record is now set to: ' + str(RECORD_ON))
        
    def restore_or_maximize_window(self):
        # Global windows state
        global WINDOW_SIZE #The default value is zero to show that the size is not maximized
        win_status = WINDOW_SIZE

        if win_status == 0:
            # If the window is not maximized
            WINDOW_SIZE = 1 #Update value to show that the window has been maxmized
            MainWindow.showMaximized()

            # Update button icon  when window is maximized
            self.btn_maximize_restore.setIcon(QtGui.QIcon(cwd + "/icons/icons/cil-window-restore.png"))#Show minized icon
        else:
            # If the window is on its default size
            WINDOW_SIZE = 0 #Update value to show that the window has been minimized/set to normal size (which is 800 by 400)
            MainWindow.showNormal()

            # Update button icon when window is minimized
            self.btn_maximize_restore.setIcon(QtGui.QIcon(cwd + "/icons/icons/cil-window-maximize.png"))#Show maximize icon

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title_bar_top.setText(_translate("MainWindow", "Main Window - Video Capture Software"))
        self.btn_hide_config.setToolTip(_translate("MainWindow", "Hide this configuration panel."))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_maximize_restore.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.CameraIDLabel.setText(_translate("MainWindow", "Camera ID"))
        self.label_user_icon.setText(_translate("MainWindow", "TO"))
        self.StopCamera.setToolTip(_translate("MainWindow", "Set-up button to process video using BirdBot ML model."))
        self.StopCamera.setText(_translate("MainWindow", " Stop Cameras"))
        self.StartCameras.setToolTip(_translate("MainWindow", "Setup button for DSLR / USB camera(s)."))
        self.StartCameras.setText(_translate("MainWindow", " Start Cameras"))
        self.captureFolder.setText(_translate("MainWindow", "B:\\BirdBot\\BirdKeras\\TensorFlow2\\YOLO_Videos"))
        self.ProcessVideoFile_5.setToolTip(_translate("MainWindow", "Set-up button to process video using BirdBot ML model."))
        self.ProcessVideoFile_5.setText(_translate("MainWindow", " Set Capture Folder"))
        self.RecordButton3.setToolTip(_translate("MainWindow", "Enable video capture."))
        self.RecordButton3.setText(_translate("MainWindow", "Record Video"))
        self.ProcessVideoFile_6.setToolTip(_translate("MainWindow", "Set-up button to process video using BirdBot ML model."))
        self.ProcessVideoFile_6.setText(_translate("MainWindow", " Stop Cameras"))
        self.ProcessVideoFile_7.setToolTip(_translate("MainWindow", "Setup button for DSLR / USB camera(s)."))
        self.ProcessVideoFile_7.setText(_translate("MainWindow", " Start Cameras"))
        self.captureFolder_2.setText(_translate("MainWindow", "B:\\BirdBot\\BirdKeras\\TensorFlow2\\YOLO_Videos"))
        self.ProcessVideoFile_8.setToolTip(_translate("MainWindow", "Set-up button to process video using BirdBot ML model."))
        self.ProcessVideoFile_8.setText(_translate("MainWindow", " Set Capture Folder"))
        self.RecordButton2.setToolTip(_translate("MainWindow", "Enable video capture."))
        self.RecordButton2.setText(_translate("MainWindow", "Record Video"))
        self.StopCamera2.setToolTip(_translate("MainWindow", "Set-up button to process video using BirdBot ML model."))
        self.StopCamera2.setText(_translate("MainWindow", " Stop Cameras"))
        self.StartCameras2.setToolTip(_translate("MainWindow", "Setup button for DSLR / USB camera(s)."))
        self.StartCameras2.setText(_translate("MainWindow", " Start Cameras"))
        self.captureFolder_4.setText(_translate("MainWindow", "B:\\BirdBot\\BirdKeras\\TensorFlow2\\YOLO_Videos"))
        self.ProcessVideoFile_12.setToolTip(_translate("MainWindow", "Set-up button to process video using BirdBot ML model."))
        self.ProcessVideoFile_12.setText(_translate("MainWindow", " Set Capture Folder"))
        self.RecordButton.setToolTip(_translate("MainWindow", "Enable video capture."))
        self.RecordButton.setText(_translate("MainWindow", "Record Video"))
        self.label_credits.setText(_translate("MainWindow", "Registered by: Tyler Odenthal"))
        self.label_version.setText(_translate("MainWindow", "v1.0.0"))
        self.actionSelectFile.setText(_translate("MainWindow", "SelectFile"))
        
    def ChangeCamera(self):
        global CURRENT_INDEX_PAGE
        
        print('Current page: ' + str(CURRENT_INDEX_PAGE))
        
        CURRENT_INDEX_PAGE = self.CurrentCameraID.value()
        
        self.stackedWidget.setCurrentIndex(CURRENT_INDEX_PAGE)
        print('Switched to page: ' + str(CURRENT_INDEX_PAGE))
        
    def StartTheCameras(self):
        times, times_2 = [], []
        
        global CAMERA_ON
        
        CAMERA_ON = True
        
        try:
            vid = cv2.VideoCapture(1, cv2.CAP_DSHOW)
            vid.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
            vid.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)
        except:
            print("Could not connect to camera 1")        
            
        try:
            vid2 = cv2.VideoCapture(2, cv2.CAP_DSHOW)
            vid2.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
            vid2.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)
        except:
            print("Could not connect to camera 2")

        # by default VideoCapture returns float instead of int
        width = int(vid.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(vid.get(cv2.CAP_PROP_FRAME_HEIGHT))
        fps = int(vid.get(cv2.CAP_PROP_FPS))
        codec = cv2.VideoWriter_fourcc(*'mp4v')
        
        out = cv2.VideoWriter("B:\BirdBot\BirdKeras\TensorFlow2\VideoCapture1.mp4", codec, 25, (1280, 720)) # output_path must be .mp4
        out2 = cv2.VideoWriter("B:\BirdBot\BirdKeras\TensorFlow2\VideoCapture2.mp4", codec, 25, (1280, 720)) # output_path must be .mp4
        
        while CAMERA_ON is True:
            
            ret1, image = vid.read()
            ret2, image2 = vid2.read()
            
            if CAMERA_ON == False:
                out.release()
                out2.release()
                break
            
            if RECORD_ON == True:
                print("RECORDING")
                out.write(image)
                out2.write(image2)
                
            if RECORD_ON == False:
                print("STOPPED RECORDING")
            
            guess_copy = image
            currentSpecies = ''
            
            t = time.localtime()
            current_time = time.strftime("%m-%d-%Y %H:%M:%S", t)
                
            # cv2.imshow('output', image)
            self.image = image
            
            # print("Camera 1: " + str(self.image.shape[0]))
            # print("Camera 1: " + str(self.image.shape[1]))

            self.image = QtGui.QImage(self.image.data, self.image.shape[1], self.image.shape[0], QtGui.QImage.Format_RGB888).rgbSwapped()
            self.image_frame.setPixmap(QtGui.QPixmap.fromImage(self.image))
            if cv2.waitKey(1) & keyboard.is_pressed('q'):
                cv2.destroyAllWindows()
                self.image_frame_hideConfig.clear()
                self.image_frame.clear()
                break
                
            # cv2.imshow('output', image)
            self.image2 = image2
            
            # print("Camera 2: " + str(self.image2.shape[0]))
            # print("Camera 2: " + str(self.image2.shape[1]))
            
            self.image2 = QtGui.QImage(self.image2.data, self.image2.shape[1], self.image2.shape[0], QtGui.QImage.Format_RGB888).rgbSwapped()
            self.image_frame_hideConfig.setPixmap(QtGui.QPixmap.fromImage(self.image2))
            self.image_frame2.setPixmap(QtGui.QPixmap.fromImage(self.image2))
            if cv2.waitKey(1) & keyboard.is_pressed('q'):
                cv2.destroyAllWindows()
                self.image_frame_hideConfig.clear()
                self.image_frame2.clear()
                break
		
        out.release()
        out2.release()
        
    def StopTheCameras(self):
        times, times_2 = [], []
        
        global CAMERA_ON
        
        CAMERA_ON = False
        
        print(CAMERA_ON)
		
        try:
            cv2.destroyAllWindows()
            self.image_frame_hideConfig.clear()
            self.image_frame.clear()
        except:
            print("Could not connect to camera 1")        
            
        try:
            cv2.destroyAllWindows()
            self.image_frame_hideConfig.clear()
            self.image_frame2.clear()
        except:
            print("Could not connect to camera 2")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
